#print "Hello World!"
#print "Hello again"
#print "I like typing this."
#print "This is fun."
#print "Yay! Printing."
#print "I'd much rather you not."
#print 'I "said" do not touch this.' #If using a quote use single quotations for the outside
#print "I will never give up."
#print "I am bigger than my problems."
print "I will become a computer programmer."